wykop/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from wykop.accounts.views import (ConfirmTosView, RegisterView, UserDetailView,
                                  UserListView, UserLoginView, UserUpdateView)

app_name = 'accounts'

urlpatterns = [
    path('rejestracja', RegisterView.as_view(), name='register'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('uzytkownicy', UserListView.as_view(), name='list'),
    path('profil/<int:pk>', UserDetailView.as_view(), name='profile'),
    path('edycja_profilu', UserUpdateView.as_view(), name='update'),
    path('regulamin', ConfirmTosView.as_view(), name='confirm_tos'),
]

wykop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from wykop.api.urls import router
from wykop.posts.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls), name='api'),
    path('', HomeView.as_view()),
    path('', include('wykop.accounts.urls')),
    path('posts/', include('wykop.posts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wykop/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    accepted_tos = models.IntegerField(default=0)

wykop/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms

from wykop.accounts.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


class ConfirmTosForm(forms.Form):
    confirm = forms.BooleanField(required=True)

wykop/accounts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView, FormView, ListView, UpdateView
from rest_framework import viewsets

from wykop.accounts.forms import ConfirmTosForm, RegisterForm
from wykop.accounts.models import User
from wykop.accounts.serializers import UserSerializer
from wykop.settings import CURRENT_TOS_VERSION


class LogoutRequiredMixin():
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse(settings.LOGIN_REDIRECT_URL))
        return super().dispatch(request, *args, **kwargs)


class RegisterView(LogoutRequiredMixin, FormView):
    form_class = RegisterForm
    template_name = 'register.html'

    def get_success_url(self):
        return reverse('posts:list')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class UserLoginView(LogoutRequiredMixin, LoginView):
    template_name = 'login.html'


class UserListView(ListView):
    model = User
    template_name = 'user_list.html'
    context_object_name = 'users'


class UserDetailView(DetailView):
    model = User
    template_name = 'user_profile.html'
    context_object_name = 'profile'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    fields = ('first_name', 'last_name', 'email')

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse(
            'accounts:profile',
            args=(self.request.user.pk, )
        )


class ConfirmTosView(LoginRequiredMixin, FormView):
    template_name = 'confirm_tos.html'
    form_class = ConfirmTosForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['tos_version'] = settings.CURRENT_TOS_VERSION
        return ctx

    def form_valid(self, form):
        user = self.request.user
        user.accepted_tos = settings.CURRENT_TOS_VERSION
        user.save()
        return super().form_valid(form)

    def get_success_url(self):
        next = self.request.GET.get('next')
        if next:
            return next
        return reverse('posts:list')


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

wykop/accounts/templates/confirm_tos.html
{% extends 'base.html' %}

{% block content %}

  Wersja regulaminu: {{ tos_version }}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Wyślij">
  </form>

{% endblock %}

wykop/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zaloguj się">
  </form>

{% endblock %}

wykop/accounts/templates/profile_box.html
    <div class="profile">
        {% if user.is_authenticated %}
            {{ user }}
            <a href="{% url 'accounts:logout' %}">wyloguj się</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">zaloguj się</a>
        {% endif %}
    </div>

wykop/accounts/templates/register.html
{% extends 'base.html' %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zarejestruj się">
  </form>

{% endblock %}

wykop/accounts/templates/user_list.html
{% extends 'base.html' %}


{% block content %}

  {% for user in users %}

    <h4>{{ user }}</h4>
    <p>
      Liczba postów: {{ user.posts.count }}
    </p>
    <hr>

  {% endfor %}

{% endblock %}

wykop/accounts/templates/user_profile.html
{% extends 'base.html' %}


{% block content %}

  {{ profile }}

  <ul>
    {% for post in profile.posts.all %}
      <li> <a href="{{ post.get_absolute_url }}"> {{ post }} </a> </li>
    {% endfor %}
  </ul>

{% endblock %}

wykop/accounts/templates/user_update.html
{% extends 'base.html' %}

{% block content %}

  <form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Zapisz">
  </form>

{% endblock %}