wykop/posts/urls.py
from django.urls import path

from wykop.posts.views import (PostCreateView, PostDeleteView, PostDetailView,
                               PostListView, PostUpdateView, VoteView)

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>', PostDetailView.as_view(), name='details'),
    path('nowy', PostCreateView.as_view(), name='create'),
    path('glosuj/<int:post_pk>', VoteView.as_view(), name='vote'),
    path('edycja/<int:pk>', PostUpdateView.as_view(), name='edit'),
    path('usun/<int:pk>', PostDeleteView.as_view(), name='delete'),
]

wykop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from wykop.api.urls import router
from wykop.posts.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls), name='api'),
    path('', HomeView.as_view()),
    path('', include('wykop.accounts.urls')),
    path('posts/', include('wykop.posts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wykop/posts/models.py
from django.db import models
from django.db.models import deletion
from django.db.models.aggregates import Sum
from django.urls import reverse
from embed_video.fields import EmbedVideoField


class Post(models.Model):
    text = models.TextField(blank=False, default='')
    title = models.CharField(max_length=128, blank=False, default='')
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey("accounts.User", deletion.PROTECT, related_name='posts')
    image = models.ImageField(upload_to='posts_images/', null=True, blank=True)
    video = EmbedVideoField(null=True, blank=True)
    nsfw = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:details", args=(self.pk, ))

    @property
    def score(self):
        return self.votes.aggregate(Sum('value'))['value__sum'] or 0


class Vote(models.Model):
    class Meta:
        unique_together = ('user', 'post')

    PLUS = 1
    MINUS = -1
    VALUE_CHOICES = (
        (PLUS, '+'),
        (MINUS, '-'),
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey("accounts.User", on_delete=deletion.PROTECT, related_name='votes')
    post = models.ForeignKey(Post, on_delete=deletion.CASCADE, related_name='votes')

wykop/posts/views.py
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView, View)
from rest_framework import viewsets

from wykop.posts.models import Post, Vote
from wykop.posts.permissions import PostPermission
from wykop.posts.serializers import PostSerializer


class HomeView(TemplateView):
    template_name = 'home.html'


class PostListView(ListView):
    model = Post
    template_name = 'posts_list.html'
    context_object_name = 'posts'
    ordering = '-created'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['search_value'] = self.request.GET.get('search')
        return ctx

    def get_queryset(self):
        qs = super().get_queryset()

        query = self.request.GET.get('search')
        if query:
            qs = qs.filter(Q(title__icontains=query) | Q(text__icontains=query))

        return qs


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_details.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = self.get_object()
        all_posts = Post.objects.order_by('-created')

        next_post = all_posts.filter(created__lt=post.created).first()
        prev_post = all_posts.filter(created__gt=post.created).last()

        context["next_post"] = next_post
        context["prev_post"] = prev_post
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'text', 'image', 'video', 'nsfw']
    template_name = 'post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'text', 'image', 'video', 'nsfw']
    template_name = 'post_create.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(author=self.request.user)

        now = timezone.now()  # from django.utils import timezone (!)
        half_hour_ago = now - timedelta(minutes=30)

        qs = qs.filter(created__gt=half_hour_ago)

        return qs


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:list')
    context_object_name = 'post'
    template_name = 'post_delete.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(author=self.request.user)
        return qs


class VoteView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        post = Post.objects.get(pk=kwargs['post_pk'])
        value = request.POST.get('value')

        if post.author == request.user:
            raise Http404

        Vote.objects.create(
            post=post,
            user=request.user,
            value=value
        )

        return HttpResponseRedirect(request.META['HTTP_REFERER'])


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [PostPermission]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

wykop/posts/templates/home.html
<b>Witaj!</b>

wykop/posts/templates/post_create.html
{% extends 'base.html' %}

{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Zapisz">
  </form>

{% endblock %}

wykop/posts/templates/post_delete.html
{% extends 'base.html' %}


{% block content %}

<form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć post "{{ post }}"?</p>
    <input type="submit" value="Tak">
    <a href="{% url 'posts:list' %}">Jednak nie.</a>
</form>

{% endblock %}

wykop/posts/templates/post_details.html
{% extends 'base.html' %}
{% load embed_video_tags %}

{% block content %}
    <h1>{{ post }}</h1>

    <p class="
        {% if post.score >= 0 %}
            good
        {% else %}
            bad
        {% endif %}
    ">
        {{ post.score }}
    <p>

    {% include 'post_vote_form.html' %}

    <p>{{ post.text }}</p>

    {% if not user.is_authenticated and post.nsfw %}
        <button class="nsfw-button" data-id="{{ post.pk }}">nsfw</button>
        <div class="nsfw-content" data-id="{{ post.pk }}">
    {% else %}
        <div>
    {% endif %}

        {% if post.image %}
            <div>
                <img class="post_image" src="{{ post.image.url }}">
            </div>
        {% endif %}
        {% if post.video %}
            {% video post.video '800x600' %}
        {% endif %}

    </div>


    <em>{{ post.created }}</em>

    {% if prev_post %}
        <p>
            <a href="{% url 'posts:details' prev_post.pk %}">poprzedni</a>
        </p>
    {% endif %}
    {% if next_post %}
        <p>
            <a href="{% url 'posts:details' next_post.pk %}">następny</a>
        </p>
    {% endif %}

    {% if user == post.author %}
        <a href="{% url 'posts:edit' post.pk %}">Edytuj</a>
    {% endif %}

    <a href="{% url 'posts:list' %}">powrót</a>
{% endblock %}

wykop/posts/templates/post_vote_form.html
{% load vote %}

{% user_vote_for_post as user_vote %}

{% if post.author != user and user_vote == 0 %}

    <form method="post" action="{% url 'posts:vote' post.pk %}">
        {% csrf_token %}
        <input type="hidden" name="value" value="1">
        <input type="submit" value="+">
    </form>

    <form method="post" action="{% url 'posts:vote' post.pk %}">
        {% csrf_token %}
        <input type="hidden" name="value" value="-1">
        <input type="submit" value="-">
    </form>

{% endif %}

wykop/posts/templates/posts_list.html
{% extends 'base.html' %}
{% load url_utils %}

<style>
    h1 {
        color: blue;
    }
</style>


{% block content %}

    <p>
        <a href="{% url 'posts:create' %}">
            Dodaj nowy post
        </a>
    </p>

    <form method="get">
        <input 
            type="search" 
            name="search" 
            placeholder="Czego szukasz" 
            value="{{ search_value|default_if_none:"" }}">
        <input type="submit" value="Szukaj">
    </form>


    {% for post in posts %}
        <a href="{% url 'posts:details' post.pk %}">
            <h2>{{ post }}</h2>
        </a>
        {% include 'post_vote_form.html' %}

        {{ post.text }}<br>
        {{ post.score }}<br>
        {{ post.created }}<br>
        {{ post.author }}<br>
        <hr>
    {% endfor %}

    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?{% url_replace 'page' page_obj.previous_page_number %}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?{% url_replace 'page' i %}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?{% url_replace 'page' page_obj.next_page_number %}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}


{% endblock %}